### ISSUE TITLE
Show countdowns for proposal submit start / end

### ISSUE THREAD

**Issue by AnaLoznianu** [ocean-tech-ship/ocean-pearl#173]
Voting begins in 5 hours.
Voting ends in 5 hours.
Voting ended 5 hours ago.
Voting next round.

Submit (proposal) begins in 5 days.
Submit (proposal) ends in 5 hours.
Submit (proposal) ended 5 hours ago.
Submit (proposal) next round

**Comment by marhali** [comment]
STATES
- when submit and vote begins
- when submit ended and vote begins
- when submit ended and vote ends
- when submit ended and vote ended
- when next round submit and vote begins [if available]
