### ISSUE TITLE
TRLO (design) unify category color across all sections

### ISSUE THREAD

**Issue by marhali** [ocean-tech-ship/ocean-pearl#196]
![Screenshot 2021-07-25 at 16.26.48.png](https://images.zenhubusercontent.com/60d756c23f238084b75a57c2/81e77cac-761e-4039-a33b-646d1ccd322e)

**Comment by Abrom8** [comment]
consider tags from voting pages

**Comment by marhali** [comment]
Closing this for now due daisyUI theme integration
