### ISSUE TITLE
Create project wide rule for the use of css z-index

### ISSUE THREAD

**Issue by Abrom8** [ocean-tech-ship/ocean-pearl#438]
- [x] choose convention
- [x] migrate existing z-index uses

**Comment by marhali** [comment]
https://www.smashingmagazine.com/2021/02/css-z-index-large-projects/

**Comment by marhali** [comment]
![image.png](https://images.zenhubusercontent.com/60dc2a39f9763363aca84e4c/8b4b72c3-9d96-4274-a8ca-8f2830e15c27)

**Comment by marhali** [comment]
Override Web3Modal z-index: `.web3modal-modal-lightbox { z-index: 10 !important; }`
