### ISSUE TITLE
[EPIC] Proposal creation on Ocean Pearl

### ISSUE THREAD

**Issue by Abrom8** [ocean-tech-ship/ocean-pearl#453]

**Comment by marhali** [comment]
We keep this as the legacy EPIC for planning the fundamentals of pearl3. The actual implementation will be focused in the following epics:

- https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/ocean-tech-ship/ocean-pearl-api/194
- https://app.zenhub.com/workspaces/oceandao-60a669231c2ed7000e90684b/issues/ocean-tech-ship/ocean-pearl-api/193
