### ISSUE TITLE
Bootstrap Tickets

### ISSUE THREAD

**Issue by marhali** [ocean-tech-ship/ocean-pearl#548]
# Bootstrap Tickets
## Backend
- api tasks
=> project
=> proposal

- coexistence solution with airtable and pearl (syncing when projects / proposal created with pearl)

- rework auth (Nuxt Auth Module, maybe backend required)

## Frontend
- management landing

- create project formula
=> page skeleton
- create proposal formula
=> page skeleton

# [EPICS]
- api management (landing)
- api project
- api proposal

- management
- project creation
- proposal creation

# API (first thoughts)

| Method | Route | Explanation |
| ----- | ------- | ------------- |
| POST | /account/login/ | Existing login route |
| POST | /account/logout/ | Existing logout route |
| GET | /account | Get account wallet & projects |
| GET | /account/projects/[id] | Get project by id and project proposals |
| POST | /account/projects/ | Create new project |
| GET | /account/projects/[id]/proposals/[id] | Get single project proposal |
| POST | /account/projects/[id]/proposals | Create new project proposal |

**Comment by Abrom8** [comment]
/account/projects/ use plural version
